#include <SoftwareSerial.h>
#include <ChainableLED.h>
#include <Adafruit_BME280.h>
#include <Wire.h>
#include "DS1307.h"
#include <SPI.h>
#include <SD.h>
#include <Bounce2.h>
#include "Main.hpp"
#include "ConfigurationHandler.hpp"
#include "InterruptionHandler.hpp"
#include "ErrorHandler.hpp"